/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YYbkcwyC52q
 */
import Link from "next/link"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1">
        <section className="w-full h-screen py-12 md:py-24 lg:py-32">
          <div className="flex flex-col items-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl items-center">Title</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                Short description about comic(?)
              </p>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100">
          <div className="container px-4 md:px-6">
            <div className="grid items-center justify-center gap-4 md:grid-cols-2 lg:gap-12">
              <img
                alt="Comic Strip"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/vercel.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">Comic Title</h3>
                  <p className="text-gray-500 dark:text-gray-400">The latest comic strip from the web comic.</p>
                  <p className="text-gray-500 dark:text-gray-400">Release Date: January 1, 2024</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid items-center justify-center gap-4 md:grid-cols-2 lg:gap-12">
              <img
                alt="Comic Strip"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/next.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">Comic Title</h3>
                  <p className="text-gray-500 dark:text-gray-400">The latest comic strip from the web comic.</p>
                  <p className="text-gray-500 dark:text-gray-400">Release Date: January 1, 2024</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
